// THIS CODE GENERATED BY GLBASIC - JUST LEAVE IT ALONE AS IT CALLS MY "main" METHOD!


#include "Evolution.h"
void __GQuitNProfile()
{
   __PPExportProf("profile.csv", __DATE__, __TIME__);
}

namespace __GLBASIC__{
#define CODEFILE_Str() (DGStr("Evolution.gbas"))
void __glb_init_globals();
int __MainGameSub_(void)
{   __PPRegisterFunction
    __glb_init_globals();
/* GBAS: C:\Users\James\Desktop\Dropbox\EvolutionRTS\Current\Source\Evolution.gbas */

												#undef __GLBNO__
												#define __GLBNO__ 0
// --------------------------------- //.

												#undef __GLBNO__
												#define __GLBNO__ 1
// Project: Evolution.

												#undef __GLBNO__
												#define __GLBNO__ 2
// Start: Saturday, November 03, 2012.

												#undef __GLBNO__
												#define __GLBNO__ 3
// IDE Version: 10.231.

												#undef __GLBNO__
												#define __GLBNO__ 4

												#undef __GLBNO__
												#define __GLBNO__ 5

												#undef __GLBNO__
												#define __GLBNO__ 6

												#undef __GLBNO__
												#define __GLBNO__ 7

												#undef __GLBNO__
												#define __GLBNO__ 8

												#undef __GLBNO__
												#define __GLBNO__ 9
main();

												#undef __GLBNO__
												#define __GLBNO__ 10

												#undef __GLBNO__
												#define __GLBNO__ 11
KEYWAIT();

												#undef __GLBNO__
												#define __GLBNO__ 12
END();
return 0;
} // end main
// ------------------------ //
DGInt __end_main__foo__()
{
   __PPRegisterFunction
return 0;
}
void __GLB_Defaults(){
__DG_RESX=800;
__DG_RESY=600;
__DG_FULLSCREEN=0;
__DG_MULTISAMPLE=0;
__DG_FRAMERATE=30;
__DG_DEBUG=0;
__DG_WANTMOUSE=GLB_WANTMOUSE_AT_START;
__DG_SCHOOLVER=0;
__glb_AppName()= "Evolution";
}

#include "glblicence.inc"
} // namespace
